version: "3.9"
services:
  server:
    networks:
      - default
    build:
      context: ./docker
      dockerfile: plannote_server
    ports:
      - "5432:5432"
  pga:
    networks:
      - default
    build:
      context: ./docker
      dockerfile: plannote_pga
    depends_on:
      - server
    ports:
      - "5433:80"
networks:
  default:
    name: custom