<#import "../../layouts/main.ftl" as layout>
<@layout.page>
    <div class="d-flex justify-content-center">
        <h2>&#128532; Something went wrong here...</h2>
    </div>
    <div class="d-flex justify-content-center">
        <h3><small class="text-muted">Our engineers are on it!</small></h3>
    </div>
    <div class="d-flex justify-content-center">
        <a href="/" class="btn btn-primary" role="button">Go home</a>
    </div>
</@layout.page>